name: update submodules

on:
  push:
    branches:
      - main
    paths:
      - 'git-training-1/**'
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Main repo checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Submodules update
        run:  |
          git submodule update --remote
          git add .
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m 'Updating submodules [skip ci]'
          git push
